<a href="https://colab.research.google.com/github/BeteLhem401/DS-bootcamp-task1/blob/main/part1_custom_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

This custom dataset contains 15
students with 5 features and a custom index.

Create Dictionary

In [2]:
student_data = {
    "Name": [
        "Abel", "Betel", "Caleb", "Dawit", "Eden",
        "Fikir", "Hana", "Iyasu", "Jemal", "Kalkidan",
        "Liya", "Marta", "Nahom", "Rahel", "Samuel"
    ],
    "Age": [20, 21, 22, 20, 23, 21, 22, 20, 24, 21, 22, 23, 20, 21, 22],
    "Gender": [
        "Male", "Female", "Male", "Male", "Female",
        "Female", "Female", "Male", "Male", "Female",
        "Female", "Female", "Male", "Female", "Male"
    ],
    "Department": [
        "CS", "IT", "DS", "CS", "SE",
        "IT", "DS", "CS", "SE", "DS",
        "IT", "CS", "DS", "SE", "IT"
    ],
    "Score": [85, 90, 78, 88, 92, 76, 84, 80, 75, 95, 89, 91, 77, 86, 83]
}

Print the Dictionary

In [3]:
student_data

{'Name': ['Abel',
  'Betel',
  'Caleb',
  'Dawit',
  'Eden',
  'Fikir',
  'Hana',
  'Iyasu',
  'Jemal',
  'Kalkidan',
  'Liya',
  'Marta',
  'Nahom',
  'Rahel',
  'Samuel'],
 'Age': [20, 21, 22, 20, 23, 21, 22, 20, 24, 21, 22, 23, 20, 21, 22],
 'Gender': ['Male',
  'Female',
  'Male',
  'Male',
  'Female',
  'Female',
  'Female',
  'Male',
  'Male',
  'Female',
  'Female',
  'Female',
  'Male',
  'Female',
  'Male'],
 'Department': ['CS',
  'IT',
  'DS',
  'CS',
  'SE',
  'IT',
  'DS',
  'CS',
  'SE',
  'DS',
  'IT',
  'CS',
  'DS',
  'SE',
  'IT'],
 'Score': [85, 90, 78, 88, 92, 76, 84, 80, 75, 95, 89, 91, 77, 86, 83]}

Create Index

In [5]:
custom_index = [
    "S001", "S002", "S003", "S004", "S005",
    "S006", "S007", "S008", "S009", "S010",
    "S011", "S012", "S013", "S014", "S015"
]

Build DataFrame

In [6]:
df_students = pd.DataFrame(student_data, index=custom_index)

#Display Dataset

In [8]:
df_students

          Name  Age  Gender Department  Score
S001      Abel   20    Male         CS     85
S002     Betel   21  Female         IT     90
S003     Caleb   22    Male         DS     78
S004     Dawit   20    Male         CS     88
S005      Eden   23  Female         SE     92
S006     Fikir   21  Female         IT     76
S007      Hana   22  Female         DS     84
S008     Iyasu   20    Male         CS     80
S009     Jemal   24    Male         SE     75
S010  Kalkidan   21  Female         DS     95
S011      Liya   22  Female         IT     89
S012     Marta   23  Female         CS     91
S013     Nahom   20    Male         DS     77
S014     Rahel   21  Female         SE     86
S015    Samuel   22    Male         IT     83

Basic summary

In [11]:
df_students.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, S001 to S015
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        15 non-null     object
 1   Age         15 non-null     int64
 2   Gender      15 non-null     object
 3   Department  15 non-null     object
 4   Score       15 non-null     int64
dtypes: int64(2), object(3)
memory usage: 720.0+ bytes

In [13]:
df_students.describe()

             Age      Score
count  15.000000  15.000000
mean   21.466667  84.600000
std     1.245946   6.310988
min    20.000000  75.000000
25%    20.500000  79.000000
50%    21.000000  85.000000
75%    22.000000  89.500000
max    24.000000  95.000000